routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/notif/{catalog?}/{invoice?}/{info?}/{status?}', function($catalog,$invoice,$info,$status){
	event(new \App\Events\NotifEvent(['catalog'=>$catalog,'invoice'=>$catalog,'info'=>$info,'status'=>$status,'note'=>'']));
});

// Route::post('/bell', function(Request $request){
// 	event(new \App\Events\NotifEvent(['catalog'=>$request->input('catalog'),'invoice'=>$request->input('invoice'),'info'=>$request->input('info'),'status'=>$request->input('position'),'note'=>'Bell']));
// });
Route::post('/bellnotif', function(Request $request){
	event(new \App\Events\NotifEvent(['catalog'=>$request->input('catalog'),'invoice'=>$request->input('invoice'),'info'=>$request->input('info'),'status'=>$request->input('position'),'note'=>'Bell']));
});
Route::post('/newtransaction', function(Request $request){
	event(new \App\Events\NotifEvent(['catalog'=>$request->input('catalog'),'invoice'=>$request->input('invoice'),'info'=>$request->input('info'),'status'=>$request->input('position'),'note'=>'Front']));
});

Route::group(['prefix'=>'auth'],function () {
	Route::post('/login', 'Auth\LoginController@authLogin');
});

Route::get('/lang', function(Request $request) {	
	\Session::put('locale', $request->bhs);
	return redirect()->back();
});

Auth::routes();
Route::get('/', 'DashboardController@index');
Route::get('/catalog-session/{catalog?}', 'DashboardController@setCatalogSession');
Route::get('/dahsboard-data', 'DashboardController@getData');
Route::get('/logout', 'DashboardController@logout');
Route::get('/email','DashboardController@sendEmail'); 

Route::get('/home', function(){
	return redirect('/');
});

// Bell
Route::group(['prefix'=>'bell'],function () {
	Route::post('/data', 'Master\BellController@getData');
});
Route::resource('bell','Master\BellController');
// End

// Customer
Route::group(['prefix'=>'customer'],function () {
	Route::post('/data', 'Master\CustomerController@getData');
});
Route::resource('customer','Master\CustomerController');
// End

// Category Item
Route::group(['prefix'=>'category'],function () {
	Route::post('/data', 'Master\CategoryController@getData');
	Route::get('/delete/{id?}', 'Master\CategoryController@destroy');
});
Route::resource('category','Master\CategoryController');
// End

// Category Addon
Route::group(['prefix'=>'categoryadd'],function () {
	Route::post('/data', 'Master\CategoryAddController@getData');
	Route::get('/delete/{id?}', 'Master\CategoryAddController@destroy');
});
Route::resource('categoryadd','Master\CategoryAddController');
// End

// User
Route::group(['prefix'=>'user'],function () {
	Route::post('/data', 'Master\UserController@getData');
	Route::get('/delete/{id?}', 'Master\UserController@destroy');
});
Route::resource('user','Master\UserController');
// End

// Subcategory
Route::group(['prefix'=>'subcategory'],function () {
	Route::post('/data', 'Master\SubCategoryController@getData');
	Route::get('/delete/{id?}', 'Master\SubCategoryController@destroy');
});
Route::resource('subcategory','Master\SubCategoryController');
// End

// Items
Route::group(['prefix'=>'items'],function () {
	Route::post('/data', 'Master\ItemsController@getData');
	Route::get('/delete/{id?}', 'Master\ItemsController@destroy');
	Route::any('/addons/{id?}', 'Master\ItemsController@addons');
	Route::any('/addaddons/{id?}', 'Master\ItemsController@addaddons');
	Route::any('/ingredient/{id?}', 'Master\ItemsController@ingredient');
	Route::get('/detailingredient/{id?}', 'Master\ItemsController@detailingredient');
	Route::post('/addingredient/{id?}', 'Master\ItemsController@addingredient');
	Route::post('/updateingredient/{id?}', 'Master\ItemsController@updateingredient');
	Route::get('/gallery/{id?}', 'Master\ItemsController@gallery');
	Route::get('/delete/addon/{id?}/{addons?}', 'Master\ItemsController@deleteaddons');
	Route::get('/delete/ingredient/{id?}/{ingredient?}', 'Master\ItemsController@deleteingredient');
	Route::get('/primaryimage/{id?}/{image?}', 'Master\ItemsController@primaryimage');
	Route::get('/deleteimage/{id?}/{image?}/{position?}', 'Master\ItemsController@deleteimage');
});
Route::resource('items','Master\ItemsController');
//End

// Material
Route::group(['prefix'=>'material'],function () {
	Route::get('/history', 'Master\MaterialController@indexHistory');
	Route::post('/history/data', 'Master\MaterialController@getDataHistory');
	Route::get('/history/detail/{id?}', 'Master\MaterialController@showHistory');
	Route::get('/history/delete/{id?}', 'Master\MaterialController@destroyHistory');
	Route::post('/history/update/{id?}', 'Master\MaterialController@updateHistory');
	Route::post('/storeqty', 'Master\MaterialController@storeqty');
	Route::post('/data', 'Master\MaterialController@getData');
	Route::get('/delete/{id?}', 'Master\MaterialController@destroy');
	Route::get('/detail/{id?}', 'Master\MaterialController@show');
	Route::any('/stock/{id?}', 'Master\MaterialController@stock');
	Route::post('/addstock/{id?}', 'Master\MaterialController@addstock');
	Route::post('/updatestock/{id?}', 'Master\MaterialController@updatestock');
	Route::get('/delete/stock/{id?}/{stock?}', 'Master\MaterialController@deletestock');
});
Route::resource('material','Master\MaterialController');
// End

// Addons
Route::group(['prefix'=>'addons'],function () {
	Route::post('/data', 'Master\AddonsController@getData');
	Route::get('/delete/{id?}', 'Master\AddonsController@destroy');
	Route::any('/serving/{id?}', 'Master\AddonsController@serving');
	Route::get('/detailserving/{id?}', 'Master\AddonsController@detailserving');
	Route::post('/addserving/{id?}', 'Master\AddonsController@addserving');
	Route::post('/updateserving/{id?}', 'Master\AddonsController@updateserving');
	Route::get('/delete/serving/{id?}/{serving?}', 'Master\AddonsController@deleteserving');
});
Route::resource('addons','Master\AddonsController');
// End

// Slider
Route::group(['prefix'=>'sliders'],function () {
	Route::post('/data', 'Master\SlidersController@getData');
	Route::get('/delete/{id?}', 'Master\SlidersController@destroy');
});
Route::resource('sliders','Master\SlidersController');
// End

// Voucher
Route::resource('voucher','Master\VoucherController');
Route::group(['prefix'=>'voucher'],function () {
	Route::post('/data', 'Master\VoucherController@getData');
	Route::get('/delete/{id?}', 'Master\VoucherController@destroy');
	Route::get('/usagevoucher/{code?}', 'Master\VoucherController@usagevoucher');
});
// End

// Package
Route::resource('package','Master\PackageController');
Route::group(['prefix'=>'package'],function () {
	Route::post('/data', 'Master\PackageController@getData');
	Route::get('/delete/{id?}', 'Master\PackageController@destroy');
	Route::any('/price/{id?}', 'Master\PackageController@price');
	Route::get('/pricedetail/{id?}', 'Master\PackageController@pricedetail');
	Route::get('/pricedelete/{id?}', 'Master\PackageController@pricedelete');
	Route::post('/addprice', 'Master\PackageController@addprice');
	Route::post('/updateprice', 'Master\PackageController@updateprice');
});
// End

// Main Features
Route::resource('mainfeatures','Master\MainFeaturesController');
Route::group(['prefix'=>'mainfeatures'],function () {
	Route::post('/data', 'Master\MainFeaturesController@getData');
	Route::get('/delete/{id?}', 'Master\MainFeaturesController@destroy');
});
// End

// Catalog
Route::resource('catalog','CatalogController');
Route::group(['prefix'=>'catalog'],function () {
	Route::post('/data', 'CatalogController@getData');
	Route::get('/delete/{id?}', 'CatalogController@destroy');
	Route::any('/items/{id?}', 'CatalogController@items');
	Route::get('/qrcode/{id?}', 'CatalogController@qrcode');
	Route::any('/additems/{id?}', 'CatalogController@additems');
	Route::get('/position/category/{catalog?}/{category?}', 'CatalogController@getPositionCategory');
	Route::get('/position/subcategory/{catalog?}/{category?}/{subcategory?}', 'CatalogController@getPositionSubCategory');
	Route::any('/change/position/{catalog?}/{me?}/{current?}/{status?}', 'CatalogController@changeStatus');
	Route::get('/delete/element/{catalog?}/{me?}/{type?}', 'CatalogController@deleteElement');
	Route::get('/available/element/{catalog?}/{me?}/{available?}', 'CatalogController@availableElement');
});
// End

Route::group(['prefix'=>'transaction'],function () {
	Route::get('/status/{invoice?}/{status?}', 'TransactionController@updatestatus');
	Route::get('/detail/{invoice?}', 'TransactionController@detail');
	Route::get('/detailpopup/{invoice?}', 'TransactionController@detailpopup');
	Route::get('/delete/item/{id?}', 'TransactionController@deleteitem');
	Route::post('/cancel/order', 'TransactionController@cancelorder');
	Route::get('/index/{status?}', 'TransactionController@index');
	Route::any('/report/{report?}/{status?}/{startdate?}/{enddate?}', 'TransactionController@report');
	Route::get('/print/{inv?}', 'TransactionController@generateStruk');
	Route::get('/printall/{print?}/{getstatus?}/{datestart?}/{dateend?}', 'TransactionController@printAll');
	Route::any('/data', 'TransactionController@getData');
	Route::any('/datamon', 'TransactionController@getDataMon');
	Route::any('/datayear', 'TransactionController@getDataYear');
});

Route::group(['prefix'=>'pos'],function () {
	Route::any('/', 'POSController@index');
	Route::any('/table', 'POSController@getTable');
	Route::any('/tablepending', 'POSController@getTablePending');
	Route::any('/data', 'POSController@getData');
	Route::post('/update', 'POSController@updateData');

app/Http/Controllers/Master/AddonsController.php
<?php

namespace App\Http\Controllers\Master;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Models\Items;
use App\Models\Recipe;
use App\Models\ItemsStock;
use App\Models\InvoiceRecipe;

use Auth;

class AddonsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['titlepage']='Add Ons';
        $data['maintitle']='Manage Add Ons';
        return view('pages.master.addons.data',$data);
    }

    public function getData(Request $request){
        $columns = ['items_name'];
        $keyword = trim($request->input('searchfield'));
        $query = Items::where('user_id',Auth::user()->id)
                        ->where('item_type','Add')
                        ->where(function($result) use ($keyword,$columns){
                            foreach($columns as $column)
                            {
                                if($keyword != ''){
                                    $result->orWhere($column,'LIKE','%'.$keyword.'%');
                                }
                            }
                        })
                        ->orderBy('id','desc');
        $data['request'] = $request->all();
        $data['getData'] = $query->paginate(10);
        $data['pagination'] = $data['getData']->links();
        return view('pages.master.addons.table',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'items_name' => 'required|min:3',
            //'imagefile_one' => 'required|max:1000|mimes:jpeg,jpg,png',
            //'items_description' => 'nullable|min:20',
            'items_price' => 'required|numeric',
        ]);
        if(Items::save_data($request)){
            $status='success';
            $message='Your request was successful.';
        }else{
            $status='error';
            $message='Oh snap! something went wrong.';
        }
        $notif=['status'=>$status,'message'=>$message];
        return response()->json($notif);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $query=Items::where('id',$id)->first();
        return $query;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'items_name' => 'required|min:3',
            'items_price' => 'required|numeric',
            //'items_description' => 'nullable|min:20',
        ]);
        if ($request->hasFile('imagefile_one')) {
            $this->validate($request, [
                'imagefile_one' => 'required|max:1000|mimes:jpeg,jpg,png'
            ]);
        }
        if(Items::update_data($request)){
            $status='success';
            $message='Your request was successful.';
        }else{
            $status='error';
            $message='Oh snap! something went wrong.';
        }
        $notif=['status'=>$status,'message'=>$message];
        return response()->json($notif);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(Items::delete_data($id)){
            $status='success';
            $message='Your request was successful.';
        }else{
            $status='error';
            $message='Oh snap! something went wrong.';
        }
        $notif=['status'=>$status,'message'=>$message];
        return response()->json($notif);
    }

    public function serving(Request $request,$id=null){
      $data['item']=$this->show($id);
      $data['material'] = ItemsStock::select('items_stock.*','items.id as itemid','items.items_name')
                                ->leftJoin('items','items_stock.item_id','items.id')
                                ->where('items.item_type','Material')
                                ->where('items.ready_stock','Y')
                                ->groupBy('items_stock.item_id')
                                ->orderBy('items.items_name','asc')
                                ->get();
      $data['detail'] = Recipe::select('recipe.*',
                          'items.items_name',
                          'items.item_unit',
                      )
                      ->leftJoin('items','recipe.item_id','=','items.id')
                      ->where('parent_id',$id)
                      ->get();
      if($request->isMethod('post')){
        return view('pages.master.addons.tableserving',$data);
      }else{
        $data['titlepage']='Manage Serving';
        $data['maintitle']='Manage Serving';
        return view('pages.master.addons.serving',$data);
      }
    }
    public function detailserving($id=null){
      $query = Recipe::select('recipe.*',
                          'items.items_name',
                          'items.item_unit',
                      )
                      ->leftJoin('items','recipe.item_id','=','items.id')
                      ->where('recipe.id',$id)
                      ->first();
      return $query;
    }
    public function addserving($id=null, Request $request){
      $this->validate($request, [
        'item_id' => 'required',
        'serving_size' => 'numeric|min:1|max:100000',
      ]);
      if(Recipe::save_data($request)){
        $status='success';
        $message='Your request was successful.';
      }else{
        $status='error';
        $message='Oh snap! something went wrong.';
      }
      $notif=['status'=>$status,'message'=>$message];
      return response()->json($notif);
    }
    public function updateserving($id=null, Request $request){
      $this->validate($request, [
        'item_id' => 'required',
        'serving_size' => 'numeric|min:1|max:100000',
      ]);
      if(Recipe::update_data($request)){
        $status='success';
        $message='Your request was successful.';
      }else{
        $status='error';
        $message='Oh snap! something went wrong.';
      }
      $notif=['status'=>$status,'message'=>$message];
      return response()->json($notif);
    }
    public function deleteserving($item=null, $addon=null){
      $check = InvoiceRecipe::where('recipe_id',$addon)->first();
      if(!empty($check)){
        $status='error';
        $message='Oh snap! The row you selected has been used for transaction data.';
      }else{
        if(Recipe::delete_data($addon)){
          $status='success';
          $message='Your request was successful.';
        }else{
          $status='error';
          $message='Oh snap! something went wrong.';
        }
      }
      $notif=['status'=>$status,'message'=>$message];
      return response()->json($notif);
    }
}

resources/views/pages/master/addons/form.blade.php
<div id="wrapVue">
    <form id="myForm" @submit.prevent="submitForm" method="post" onsubmit="return false;" enctype="multipart/form-data">
        <input type="hidden" id="id" name="id" class="form-control"/>
        <input type="hidden" id="item_image_one" name="item_image_one" class="form-control"/>
        <input type="hidden" id="item_image_two" name="item_image_two" class="form-control"/>
        <input type="hidden" id="item_image_three" name="item_image_three" class="form-control"/>
        <input type="hidden" id="item_image_four" name="item_image_four" class="form-control"/>
        <input type="hidden" id="item_image_primary" name="item_image_primary" class="form-control"/>
        <div class="modal fade" id="modalForm" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-xl" role="document">
                <div class="modal-content">
                    <!-- Form Loader -->
                    <div class="formLoader">
                        <div class="jumper">
                            <div></div>
                            <div></div>
                            <div></div>
                        </div>
                    </div>
                    <!-- End -->
                    <div class="modal-header">
                        <h5 class="modal-title" id="titleModal"></h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div id="modalContent" class="modal-body">
                        <div class="row">
                            <div class="col-md-5">
                                <div class="position-relative form-group">
                                    <label>Add On Name <sup class="text-danger">* (Required)</sup></label>
                                    <input type="text" id="items_name" name="items_name" class="form-control"/>
                                    <div v-if="formErrors['items_name']" class="errormsg alert alert-danger mt-1">
                                      @{{ formErrors['items_name'][0] }}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="position-relative form-group">
                                    <label>Price <sup class="text-danger">* (Required)</sup></label>
                                    <input type="text" id="items_price" name="items_price" class="form-control"/>
                                    <span class="text-danger">{{ $errors->first('items_price') }}</span>
                                    <div v-if="formErrors['items_price']" class="errormsg alert alert-danger mt-1">
                                      @{{ formErrors['items_price'][0] }}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="position-relative form-group">
                                    <label>Image</label>
                                    <input type="file" id="imagefile_one" name="imagefile_one" class="form-control"/>
                                    <div v-if="formErrors['imagefile_one']" class="errormsg alert alert-danger mt-1">
                                      @{{ formErrors['imagefile_one'][0] }}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4 d-none">
                                <div class="position-relative form-group">
                                    <label>Available</label>
                                    <select id="ready_stock" name="ready_stock" class="form-control">
                                      <option value="Y">
                                        Yes
                                      </option>
                                      <option value="N">
                                        No
                                      </option>
                                    </select>
                                    <span v-if="formErrors['ready_stock']" class="errormsg">@{{ formErrors['ready_stock'][0] }}</span>
                                </div>
                            </div>
                        </div>
                        <div class="position-relative form-group">
                            <label for="myLabel" class="">Description</label>
                            <textarea id="items_description" name="items_description" class="form-control" rows="10"></textarea>
                            <div v-if="formErrors['items_description']" class="errormsg alert alert-danger mt-1">
                              @{{ formErrors['items_description'][0] }}
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save Data</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<script type="text/javascript">
    new Vue({
        el: "#wrapVue",
        data() {
            return {
                csrf: "",
                formErrors: {},
                notif: [],
            };
        },
        mounted: function () {
            this.csrf = "{{ csrf_token() }}";
            let self = this;
        },
        methods: {
            submitForm: function (e) {
                submitForm();
                $('.errormsg').hide();
                var form = e.target || e.srcElement;
                if($("#id").val() > 0){
                  var action = "{{ route('addons.update',0) }}";
                  var put = form.querySelector('input[name="_method"]').value;
                }else{
                  var action = "{{ route('addons.store') }}";
                  var put = '';
                }
                var csrfToken = "{{ csrf_token() }}";

                let datas = new FormData();
                datas.append("id", $("#id").val());
                datas.append("item_image_one", $("#item_image_one").val());
                datas.append("item_image_two", $("#item_image_two").val());
                datas.append("item_image_three", $("#item_image_three").val());
                datas.append("item_image_four", $("#item_image_four").val());
                datas.append("item_image_primary", $("#item_image_primary").val());
                datas.append("items_name", $("#items_name").val());
                datas.append("items_price", $("#items_price").val());
                datas.append("items_discount", 0);
                //datas.append("ready_stock", $("#ready_stock").val());
                datas.append('imagefile_one', document.getElementById('imagefile_one').files[0]);
                datas.append("items_description", $("#items_description").val());
                datas.append("items_youtube", '');
                datas.append("items_color", '');
                datas.append("item_type", 'Add');

                axios.post(action, datas, {
                        headers: {
                            "X-CSRF-TOKEN": csrfToken,
                            "X-HTTP-Method-Override": put,
                            Accept: "application/json",
                        },
                    })
                    .then((response) => {
                        let self = this;
                        var notif = response.data;
                        var getstatus = notif.status;
                        if (getstatus == "success") {
                            $("#modalForm").modal("hide");
                            afterSubmitForm();
                            loadView();
                        }else{
                            afterSubmitForm();
                            toastr.error(notif.message);
                        }
                    })
                    .catch((error) => {
                        afterSubmitForm();
                        $('.errormsg').show();
                        this.formErrors = error.response.data.errors;
                    });
                
            },
        },
    });
</script>

resources/views/pages/master/addons/gallery.blade.php
<div class="row">
	@if(!empty($getData['item_image_one']))
	<div class="col-md-6">
		<div class="form-group text-center">
			<a href="javascript:void(0)" data-featherlight="{{ myFunction::getProtocol().str_replace('/thumbs','',$getData['item_image_one']) }}">
				<img src="{{ myFunction::getProtocol().$getData['item_image_one'] }}" class="img-fluid img-thumbnail">
			</a>
			@if($getData['item_image_one']!=$getData['item_image_primary'])
			<div class="mt-3">
				<a href="javascript:void(0)" class="btn-hover-shine btn btn-info btn-shadow btn-sm" onclick="setPrimary('{{ basename(parse_url($getData['item_image_one'])['path']) }}','{{ $getData['id'] }}')">Set as Primary</a>
				<a href="javascript:void(0)" class="btn-hover-shine btn btn-danger btn-shadow btn-sm" onclick="deleteImage('{{ basename(parse_url($getData['item_image_one'])['path']) }}','{{ $getData['id'] }}','one')">Delete Images</a>
			</div>
			@else
			<div class="mt-3">
				<a href="javascript:void(0)" class="btn-hover-shine btn btn-success btn-shadow btn-sm btn-block">Primary Image</a>
			</div>
			@endif
		</div>
	</div>
	@endif
	@if(!empty($getData['item_image_two']))
	<div class="col-md-6">
		<div class="form-group">
			<a href="javascript:void(0)" data-featherlight="{{ myFunction::getProtocol().str_replace('/thumbs','',$getData['item_image_two']) }}">
				<img src="{{ myFunction::getProtocol().$getData['item_image_two'] }}" class="img-fluid img-thumbnail">
			</a>
			@if($getData['item_image_two']!=$getData['item_image_primary'])
			<div class="mt-3">
				<a href="javascript:void(0)" class="btn-hover-shine btn btn-info btn-shadow btn-sm" onclick="setPrimary('{{ basename(parse_url($getData['item_image_two'])['path']) }}','{{ $getData['id'] }}')">Set as Primary</a>
				<a href="javascript:void(0)" class="btn-hover-shine btn btn-danger btn-shadow btn-sm" onclick="deleteImage('{{ basename(parse_url($getData['item_image_two'])['path']) }}','{{ $getData['id'] }}','two')">Delete Images</a>
			</div>
			@else
			<div class="mt-3">
				<a href="javascript:void(0)" class="btn-hover-shine btn btn-success btn-shadow btn-sm btn-block">Primary Image</a>
			</div>
			@endif
		</div>
	</div>
	@endif
	@if(!empty($getData['item_image_three']))
	<div class="col-md-6">
		<div class="form-group">
			<a href="javascript:void(0)" data-featherlight="{{ myFunction::getProtocol().str_replace('/thumbs','',$getData['item_image_three']) }}">
				<img src="{{ myFunction::getProtocol().$getData['item_image_three'] }}" class="img-fluid img-thumbnail">
			</a>
			@if($getData['item_image_three']!=$getData['item_image_primary'])
			<div class="mt-3">
				<a href="javascript:void(0)" class="btn-hover-shine btn btn-info btn-shadow btn-sm" onclick="setPrimary('{{ basename(parse_url($getData['item_image_three'])['path']) }}','{{ $getData['id'] }}')">Set as Primary</a>
				<a href="javascript:void(0)" class="btn-hover-shine btn btn-danger btn-shadow btn-sm" onclick="deleteImage('{{ basename(parse_url($getData['item_image_three'])['path']) }}','{{ $getData['id'] }}','three')">Delete Images</a>
			</div>
			@else
			<div class="mt-3">
				<a href="javascript:void(0)" class="btn-hover-shine btn btn-success btn-shadow btn-sm btn-block">Primary Image</a>
			</div>
			@endif
		</div>
	</div>
	@endif
	@if(!empty($getData['item_image_four']))
	<div class="col-md-6">
		<div class="form-group">
			<a href="javascript:void(0)" data-featherlight="{{ myFunction::getProtocol().str_replace('/thumbs','',$getData['item_image_four']) }}">
				<img src="{{ myFunction::getProtocol().$getData['item_image_four'] }}" class="img-fluid img-thumbnail">
			</a>
			@if($getData['item_image_four']!=$getData['item_image_primary'])
			<div class="mt-3">
				<a href="javascript:void(0)" class="btn-hover-shine btn btn-info btn-shadow btn-sm" onclick="setPrimary('{{ basename(parse_url($getData['item_image_four'])['path']) }}','{{ $getData['id'] }}')">Set as Primary</a>
				<a href="javascript:void(0)" class="btn-hover-shine btn btn-danger btn-shadow btn-sm" onclick="deleteImage('{{ basename(parse_url($getData['item_image_four'])['path']) }}','{{ $getData['id'] }}','four')">Delete Images</a>
			</div>
			@else
			<div class="mt-3">
				<a href="javascript:void(0)" class="btn-hover-shine btn btn-success btn-shadow btn-sm btn-block">Primary Image</a>
			</div>
			@endif
		</div>
	</div>
	@endif
</div>

resources/views/pages/master/addons/tableserving.blade.php
<div class="table-responsive">
	<table class="align-middle mb-0 table table-borderless table-striped table-hover">
	    <thead>
	        <tr>
	            <th nowrap class="pt-4 pb-4 ">Material Name</th>
	            <th class="pt-4 pb-4 text-right" nowrap>Serving Size</th>
	            <th class="pt-4 pb-4 text-center" nowrap>Actions</th>
	        </tr>
	    </thead>
	    <tbody>
	        @foreach($detail as $key => $vdetail)
	        <tr>
	            <td nowrap>{{ $vdetail['items_name'] }}</td>
	            <td class="text-right" nowrap>{{ $vdetail['serving_size'] }} {{ $vdetail['item_unit'] }}</td>
	            <td class="text-center" nowrap>
	                <div role="group" class="btn-group-sm btn-group btn-group-toggle">
	                	<a href="javascript:void(0)" data-id="{{ $vdetail['id'] }}" class="editlink btn btn-shadow btn-info">Edit</a>
                        <a href="javascript:void(0)" data-id="{{ $vdetail['id'] }}" data-item="{{ $item['id'] }}" class="deletelink btn btn-shadow btn-danger">Delete</a>
	                </div>
	            </td>
	        </tr>
	        @endforeach
	    </tbody>
	</table>
</div>